mapping_to_default:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  11: 11
  12: 12
  13: 13
  14: 13
  15: 14
  16: 15
  17: 16
  18: 16
  19: 18
  20: 17
  21: 19
  22: 20
  23: 21
  24: 22
  25: 23
  26: 23
  27: 24
  28: 25
  29: 26
  30: 27
  31: 28
  32: 1
  33: 30
  34: 31
  35: 32
  36: 33
  37: 34
names:
  0: Lamp
  1: Cupboard
  2: Cabinetry
  3: Wardrobe
  4: Pillow
  5: Bathroom cabinet
  6: Kitchen & dining room table
  7: Gas stove
  8: Washing machine
  9: Chair
  10: Mirror
  11: Microwave oven
  12: Toilet
  13: Sofa bed
  14: Couch
  15: Shelf
  16: Sink
  17: Table
  18: Desk
  19: Television
  20: Refrigerator
  21: Ceiling fan
  22: Oven
  23: Shower
  24: Bathtub
  25: Kitchen utensil
  26: Kitchenware
  27: Kitchen appliance
  28: Bidet
  29: Nightstand
  30: Heater
  31: Piano
  32: Cupboard
  33: Coffee table
  34: Coffeemaker
  35: Closet
  36: Bathroom accessory
  37: Dishwasher
path: /Users/phamvy/Projects/dataset/furniture_dataset
train: images/train
val: images/valid
