mapping_id:
  0: -1
  1: -1
  2: -1
  3: -1
  4: -1
  5: 0
  6: 1
  7: -1
  8: -1
  9: -1
  10: -1
  11: -1
  12: -1
  13: -1
  14: -1
  15: 2
  16: -1
  17: -1
  18: -1
  19: 3
  20: -1
  21: -1
  22: 4
  23: -1
  24: -1
  25: -1
  26: -1
  27: -1
  28: -1
  29: -1
  30: -1
  31: -1
  32: -1
  33: -1
  34: -1
  35: -1
  36: -1
  37: 5
  38: -1
  39: 6
  40: -1
  41: 7
  42: -1
  43: -1
  44: -1
  45: -1
  46: -1
  47: -1
  48: -1
  49: 11
  50: -1
  51: -1
  52: -1
  53: -1
  54: -1
  55: -1
  56: -1
  57: 8
  58: -1
  59: -1
  60: -1
  61: -1
  62: -1
  63: -1
  64: -1
  65: -1
  66: -1
mapping_names:
  0: bathroom/toilet
  1: bedroom
  2: closet
  3: corridor
  4: dining_room
  5: kitchen
  6: laundry_room
  7: living_room
  8: staircase
  9: balcony
  10: terrace
  11: working_room
  12: tabernacle_room
names:
  0: airport_inside
  1: artstudio
  2: auditorium
  3: bakery
  4: bar
  5: bathroom
  6: bedroom
  7: bookstore
  8: bowling
  9: buffet
  10: casino
  11: children_room
  12: church_inside
  13: classroom
  14: cloister
  15: closet
  16: clothingstore
  17: computerroom
  18: concert_hall
  19: corridor
  20: deli
  21: dentaloffice
  22: dining_room
  23: elevator
  24: fastfood_restaurant
  25: florist
  26: gameroom
  27: garage
  28: greenhouse
  29: grocerystore
  30: gym
  31: hairsalon
  32: hospitalroom
  33: inside_bus
  34: inside_subway
  35: jewelleryshop
  36: kindergarden
  37: kitchen
  38: laboratorywet
  39: laundromat
  40: library
  41: livingroom
  42: lobby
  43: locker_room
  44: mall
  45: meeting_room
  46: movietheater
  47: museum
  48: nursery
  49: office
  50: operating_room
  51: pantry
  52: poolinside
  53: prisoncell
  54: restaurant
  55: restaurant_kitchen
  56: shoeshop
  57: stairscase
  58: studiomusic
  59: subway
  60: toystore
  61: trainstation
  62: tv_studio
  63: videostore
  64: waitingroom
  65: warehouse
  66: winecellar

using_mapping: true
