path: ../room_type/rever  # dataset root dir
train: train  # train images (relative to 'path') 1281167 images
val: val  # val images (relative to 'path') 50000 images
test:  # test images (optional)


mapping_id:
  0: 9
  1: 0
  2: 1
  3: 4
  4: -1
  5: 3
  6: 5
  7: 6
  8: 7
  9: 9
  10: 8
  11: 12
  12: 10
  13: 0
  14: -1
  15: 2
  16: 11
mapping_names:
  0: bathroom/toilet
  1: bedroom
  2: closet
  3: corridor
  4: dining_room
  5: kitchen
  6: laundry_room
  7: living_room
  8: staircase
  9: balcony
  10: terrace
  11: working_room
  12: tabernacle_room
names:
  0: balcony
  1: bathroom
  2: bedroom
  3: dining_room
  4: empty_room
  5: hallway
  6: kitchen
  7: laundry_room
  8: living_room
  9: loggia
  10: stairs
  11: tabernacle_room
  12: terrace
  13: toilet
  14: undefined
  15: walkin_closet
  16: working_room

using_mapping: true

