classes:
  0: lamp
  1: cupboard
  2: cabinetry
  3: wardrobe
  4: pillow
  5: bathroom_cabinet
  6: kitchen_and_dining_room_table
  7: gas_stove
  8: washing_machine
  9: chair
  10: mirror
  11: microwave/oven
  12: toilet
  13: sofa_bed/couch
#  14: couch
  14: shelf
  15: sink
  16: table/desk
#  17: desk
  17: refrigerator
  18: television
  19: ceiling_fan
  20: oven
  21: shower
  22: bathtub
  23: kitchenware (non-electrical)
  24: kitchen_appliance (electrical)
  25: bidet
  26: nightstand
  27: heater
  28: piano
  29: coffee_table
  30: coffeemaker
  31: closet
  32: bathroom_accessory
  33: dishwasher
  34: fan
  35: vacuum_cleaner
  36: water_heater
  37: kitchen_cabinet
  38: makeup_table
  39: bed
  40: basin
  41: kitchen_hood
  42: fire_detector
  43: air_conditioner
  #  25: home_appliance
#  24: kitchen_utensil
